# Generated by Django 5.1.7 on 2025-03-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
